accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>',views.view_profile,name="profile")
]

accounts/models.py
from distutils.command import upload
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class CustomUser(AbstractUser):
    phone_number = models.IntegerField(blank=True,null=True)
    photo=models.ImageField(upload_to="profile/pic/",verbose_name="Your Photo")

accounts/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from .models import CustomUser

class CustomUserForm(forms.ModelForm):
    password2=forms.CharField(required=True,widget=forms.PasswordInput(attrs={"class":"form-control"}))
    class Meta:
        model = CustomUser
        fields = ['photo','first_name','last_name','username','email','phone_number','password','password2']
        widgets = {
            "first_name":forms.TextInput(attrs={"class":"form-control"}),
            "last_name":forms.TextInput(attrs={"class":"form-control"}),
            "username":forms.TextInput(attrs={"class":"form-control"}),
            "email":forms.EmailInput(attrs={"class":"form-control"}),
            "phone_number":forms.NumberInput(attrs={"class":"form-control"}),
            "password":forms.PasswordInput(attrs={"class":"form-control"}),
            "password2":forms.PasswordInput(attrs={"class":"form-control"}),
            "photo":forms.FileInput(attrs={"class":"form-control"}),
        }

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib import auth,messages
from .models import CustomUser
from django.http import Http404
from accounts.forms import CustomUserForm
from django.contrib.auth.hashers import make_password

# Create your views here.


def     register(request):
    if request.user.is_authenticated:
        if request.user:
            return redirect('home:home')
    context={"forms":CustomUserForm()}
    if request.method=="POST":
        data=request.POST.copy()

        password1=data.get('password','')
        password2=data.get('password2','')
        
        data['password'] = make_password(password1)
        forms=CustomUserForm(data,request.FILES)

        if password1!=password2:
            context['forms']=forms
            context["errors"]="Password Didnot Match"
            return render(request,'accounts/signup.html',context)

        if forms.is_valid():
            forms.save()
            user = auth.authenticate(username=data.get('username'), password=data.get('password2'))
            if user is not None:
                auth.login(request, user)

                messages.success(request,
                             f'Congratulation You have been registered in our system.')
                return redirect('home:home')
        else:
            context['forms']=forms
    return render(request,'accounts/signup.html',context)



def login(request):
    context={}
    if request.user.is_authenticated:
        if request.user:
            return redirect('home:home')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            messages.success(request,
                             f'Congratulation You Logged into our system.')
            return redirect('home:home')
        else:
            context['errors'] = "User name or password is incorrect"
            context['username'] = username
            return render(request, 'accounts/login.html', context)
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth.logout(request)
    return redirect('home:home')


def view_profile(request,username):
    try:
        context={"profile":CustomUser.objects.get(username=username)}
        # import pdb;pdb.set_trace()
        if request.user.username == context['profile'].username or request.user.is_superuser:
            return render(request,'accounts/profile.html',context)
    except:
        pass
    raise Http404

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - Dhoran Nepal</title>

    <!-- Favicon -->
    <link href="{% static 'assets/images/logo.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'assets/plugin/poppins_font/poppins_font.css' %}">
    <!-- Material Design Icon -->
    <link rel="stylesheet" href="{% static 'assets/fonts/material-design/css/materialdesignicons.css' %}">
    <!-- Bootstrap 5 CDN Link -->
    <link href="{% static 'assets/plugin/bootstrap/css/bootstrap5.min.css' %}" rel="stylesheet">
    <!-- Custom CSS Link -->
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">

</head>

<body style="">

<!-- Back to top button -->
<button type="button" class="btn btn-primary btn-floating btn-sm" title="Back To Top" id="btn-back-to-top">
    <i class="fas fa-arrow-up"></i>
</button>

<!-- Section: Design Block -->
<section class="text-center text-lg-start">

    <div class="container py-4 mt-5">
        <div class="row g-0 align-items-center mt-5">
          <a href="/" class="previous">&laquo; Back To Home</a>
            <div class="login-img col-lg-6 mb-5 mb-lg-0 mt-5">
                <img src="{% static 'assets/images/logo.png' %}" class="w-100 rounded-4" alt=""/>
            </div>
            <div class="col-lg-6 mb-5 mb-lg-0">
                <div class="card cascading-right">
                    <div class="card-body p-5 text-center">
                        {% if errors %}
                            <div class="alert alert-danger mt-2">    {{ errors }}</div>
                        {% endif %}

                        <h2 class="fw-bold mb-5"><span>Login Dhoran Nepal</span></h2>
                        <form method="post">
                            {% csrf_token %}
                            <!-- Email input -->
                            <div class="form-outline mb-4">
                                <label class="form-label"><i class=" fa fa-user"></i> Username</label>
                                <input type="text" name="username" value="{{ username }}" id="form3Example3"
                                       class="form-control" required/>
                            </div>

                            <!-- Password input -->
                            <div class="form-outline mb-4">
                                <label class="form-label" for="password"><i class="fa fa-key"></i> Password</label>
                                <input type="password" name="password" id="password" class="form-control"
                                       required/>
                                <span class="" onclick="password_show_hide();">
                                        <i class="fas fa-eye" id="show_eye"></i>
                                        <i class="fas fa-eye-slash d-none" id="hide_eye"></i>
                                    </span>
                            </div>
                            

                            <!-- Submit button -->
                            <input type="submit" value="Sign In" class="btn btn-primary btn-block mt-5 mb-2">
                        </form>
                        <a href="{% url 'accounts:register' %}" class="btn btn-primary btn-block mt-5 mb-2">Sign Up</a>
                    </div>
                </div>
            </div>

        </div>
    </div>


</section>
<center>
    <footer class="footer">
			<ul class="list-inline">
				<li><span>Copyright &copy; Dhoran Nepal,
						
					</span></li>

			</ul>
		</footer>
</center>
<!-- Section: Design Block -->
<script>
    const input = document.getElementById('id_captcha_1');
    // ✅ Remove required attribute
    input.removeAttribute('required');

</script>

<script src="{% static 'assets/scripts/all.min.js' %}"></script>

<script>
    function password_show_hide() {
        var x = document.getElementById("password");
        var show_eye = document.getElementById("show_eye");
        var hide_eye = document.getElementById("hide_eye");
        hide_eye.classList.remove("d-none");
        if (x.type === "password") {
            x.type = "text";
            show_eye.style.display = "none";
            hide_eye.style.display = "block";
        } else {
            x.type = "password";
            show_eye.style.display = "block";
            hide_eye.style.display = "none";
        }
    }
</script>
</body>

</html>

accounts/templates/accounts/profile.html
{% extends 'home/base.html'%}
{% load static%}

{%block body%}  
<section class="product spad">
  <div class="container">
      <div class="row">
          <div class="col-lg-12">
              <ul class="filter__controls">
                  <li class="active" data-filter=".best-seller" id="bestest">
                    <h3>My Profile</h3><br>
                    <img src="{{profile.photo.url}}" height="200" width="200"><br>
                    Username: {{profile.username}}<br>
                    Full Name: {{profile.first_name.upper}} {{profile.last_name.upper}}<br>
                    Email: {{profile.email}}<br>
                    Phone: {{profile.phone_number}}<br>
                  </li>
                  
              </ul>
          </div>
      </div>
  </div>
</section>
{% comment %} <section class="product spad">
  <div class="container">
      <div class="row">
        <div class="log-form">
            <h2>Login to your account</h2>
            <form>
              <input type="text" title="username" placeholder="username" />
              <input type="password" title="username" placeholder="password" />
              <button type="submit" class="btn">Login</button>
              <a class="forgot" href="#">Forgot Username?</a>
            </form>
          </div><!--end log form -->

          </div>
        </div>
      </div>
    </div>
  </section> {% endcomment %}

  {%endblock%}

accounts/templates/accounts/signup.html
{% comment %} {% extends 'home/base.html'%}
{% load static%}

{%block body%}  
<section class="product spad">
  <div class="container">
      <div class="row">
          <div class="col-lg-12">
              <ul class="filter__controls">
                  <li class="active" data-filter=".best-seller" id="bestest">
                    <h3>Register</h3><br>

                    <form method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      {{errors}}<br>
                      {{forms.as_p}}
                      <button type="submit" class="btn btn-success">Sign Up</button><br><br>
                      <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>

                    </form>  
              
                  </li>
                  
              </ul>
          </div>
      </div>
  </div>
</section>
{% comment %} <section class="product spad">
  <div class="container">
      <div class="row">
        <div class="log-form">
            <h2>Login to your account</h2>
            <form>
              <input type="text" title="username" placeholder="username" />
              <input type="password" title="username" placeholder="password" />
              <button type="submit" class="btn">Login</button>
              <a class="forgot" href="#">Forgot Username?</a>
            </form>
          </div><!--end log form -->

          </div>
        </div>
      </div>
    </div>
  </section> {% endcomment %}

  

  {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - Dhoran Nepal</title>

    <!-- Favicon -->
    <link href="{% static 'assets/images/logo.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'assets/plugin/poppins_font/poppins_font.css' %}">
    <!-- Material Design Icon -->
    <link rel="stylesheet" href="{% static 'assets/fonts/material-design/css/materialdesignicons.css' %}">
    <!-- Bootstrap 5 CDN Link -->
    <link href="{% static 'assets/plugin/bootstrap/css/bootstrap5.min.css' %}" rel="stylesheet">
    <!-- Custom CSS Link -->
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">

</head>

<body style="">

<!-- Back to top button -->
<button type="button" class="btn btn-primary btn-floating btn-sm" title="Back To Top" id="btn-back-to-top">
    <i class="fas fa-arrow-up"></i>
</button>

<style>
  
  
  .previous {
  color: black;
  text-decoration: none;
  display: inline-block;
  padding: 8px 16px;
  }
  
</style>

<!-- Section: Design Block -->
<section class="text-center text-lg-start">

    <div class="container py-4 mt-5">
        <div class="row g-0 align-items-center mt-5">
          <a href="/" class="previous">&laquo; Back To Home</a>
          <br>
          <br>

            {% comment %} <div class="login-img col-lg-6 mb-5 mb-lg-0 mt-5">
                <img src="{% static 'assets/images/logo.png' %}" class="w-100 rounded-4" alt=""/>
            </div> {% endcomment %}
            <div class="col-lg-12 mb-5 mb-lg-0">
                <div class="card cascading-right">
                    <div class="card-body p-5 text-center">
                        {% if errors %}
                            <div class="alert alert-danger mt-2">    {{ errors }}</div>
                        {% endif %}

                        <h2 class="fw-bold mb-5"><span>Register Dhoran Nepal</span></h2>
                        <form method="post" enctype='multipart/form-data'>
                            {% csrf_token %}
                            <!-- Email input -->
                            {% comment %} <div class="form-outline mb-4">
                                <label class="form-label"><i class=" fa fa-user"></i> Username</label>
                                <input type="text" name="username" value="{{ username }}" id="form3Example3"
                                       class="form-control" required/>
                            </div>

                            <!-- Password input -->
                            <div class="form-outline mb-4">
                                <label class="form-label" for="password"><i class="fa fa-key"></i> Password</label>
                                <input type="password" name="password" id="password" class="form-control"
                                       required/>
                                <span class="" onclick="password_show_hide();">
                                        <i class="fas fa-eye" id="show_eye"></i>
                                        <i class="fas fa-eye-slash d-none" id="hide_eye"></i>
                                    </span>
                            </div> {% endcomment %}

                            {{forms.as_p}}
                            

                            <!-- Submit button -->
                            <input type="submit" value="Sign Up" class="btn btn-primary btn-block mt-5 mb-2">
                        </form>
                        <a href="{% url 'accounts:login' %}" class="btn btn-primary btn-block mt-5 mb-2">Login</a>
                    </div>
                </div>
            </div>

        </div>
    </div>


</section>
<center>
    <footer class="footer">
			<ul class="list-inline">
				<li><span>Copyright &copy; Dhoran Nepal,
						
					</span></li>

			</ul>
		</footer>
</center>
<!-- Section: Design Block -->
<script>
    const input = document.getElementById('id_captcha_1');
    // ✅ Remove required attribute
    input.removeAttribute('required');

</script>

<script src="{% static 'assets/scripts/all.min.js' %}"></script>

<script>
    function password_show_hide() {
        var x = document.getElementById("password");
        var show_eye = document.getElementById("show_eye");
        var hide_eye = document.getElementById("hide_eye");
        hide_eye.classList.remove("d-none");
        if (x.type === "password") {
            x.type = "text";
            show_eye.style.display = "none";
            hide_eye.style.display = "block";
        } else {
            x.type = "password";
            show_eye.style.display = "block";
            hide_eye.style.display = "none";
        }
    }
</script>
</body>

</html>